# Generated by Django 5.0.2 on 2024-03-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_customu_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
