# Generated by Django 5.0.2 on 2024-03-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='sig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=120)),
            ],
        ),
    ]
